# Generated by Django 5.0.1 on 2024-01-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedfile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='created_by',
        ),
    ]
